name: CI Moving Average

on:
  schedule:
    # JST 02:07 (UTC 17:07)
    - cron: '7 17 * * *'
  workflow_dispatch:
    inputs:
      since_days:
        description: 'Number of days to analyze'
        required: false
        default: '14'
        type: string

permissions:
  contents: read

jobs:
  compute-mavg:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Compute CI Moving Average
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # GitHub CLI認証確認
          gh auth status
          
          # 移動平均計算実行
          DAYS="${{ inputs.since_days || '14' }}"
          python scripts/ci/compute_2w_mavg.py \
            --since-days "$DAYS" \
            --output "artifacts/ci/summary-$(date +%Y%m%d).json"
            
          # 結果確認
          echo "Generated summary file:"
          ls -la artifacts/ci/
          cat artifacts/ci/summary-*.json | head -20
          
      - name: Upload CI Summary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-mavg-${{ github.run_id }}
          path: artifacts/ci/
          retention-days: 30
          
      - name: Summary
        run: |
          SUMMARY_FILE=$(ls artifacts/ci/summary-*.json | head -1)
          if [ -f "$SUMMARY_FILE" ]; then
            echo "## CI Moving Average Report" >> $GITHUB_STEP_SUMMARY
            echo "Generated: $(date)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # JSONから主要値を抽出（jqが利用可能な環境想定）
            OVERALL_RATE=$(python -c "import json; data=json.load(open('$SUMMARY_FILE')); print(data['overall']['success_rate'])")
            WINDOW_DAYS=$(python -c "import json; data=json.load(open('$SUMMARY_FILE')); print(data['window_days'])")
            
            echo "- **Period**: $WINDOW_DAYS days" >> $GITHUB_STEP_SUMMARY
            echo "- **Overall Success Rate**: $OVERALL_RATE%" >> $GITHUB_STEP_SUMMARY
            echo "- **Target**: 70.0%" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Full report available in artifacts." >> $GITHUB_STEP_SUMMARY
          fi