name: ci-mcp-api-boundary
on:
  pull_request:
    paths:
      - ".github/workflows/ci-mcp-api-boundary.yml"
      - "docs/CI/MCP_API_BOUNDARY_STAGE_C.md"
  workflow_dispatch:

jobs:
  api-boundary:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Assert GET is allowed (repo metadata)
        run: |
          set -euo pipefail
          gh api /repos/${{ github.repository }} -q '.name' | grep -i ucomm
      - name: Assert boundary limits (minimal GET-only)
        run: |
          set -euo pipefail
          echo "GET /repos/${{ github.repository }} metadata"
          gh api /repos/${{ github.repository }} | jq .name
          echo "✅ Stage C boundary test passed (read-only access verified)"
      - name: Mask outputs
        run: |
          echo "::add-mask::${{ github.token }}"