name: CI Moving Average

on:
  # 既存のスケジュールは必要に応じて調整してください（例は毎日 00:30 UTC）
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
    inputs:
      since_days:
        description: "集計対象：直近 何日分を見るか（デフォルト 14 日）"
        required: true
        default: "14"
        type: string

permissions:
  contents: read
  actions: read

concurrency:
  group: ci-mavg-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compute-mavg:
    name: compute-mavg
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare dirs
        run: mkdir -p artifacts/ci

      - name: GitHub CLI auth status
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh auth status

      # ←ここが暫定安定化の肝。失敗してもジョブを赤にしない。
      - name: Compute 2-week moving average (tolerant)
        id: compute
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          DAYS: ${{ inputs.since_days || '14' }}
        run: |
          set -Eeuo pipefail
          outfile="artifacts/ci/summary-$(date +%Y%m%d).json"
          # スクリプトが落ちてもワーニング＆プレースホルダで進行
          if ! python scripts/ci/compute_2w_mavg.py \
                --since-days "${DAYS:-14}" \
                --output "$outfile"; then
            echo "::warning::compute_2w_mavg.py failed; writing placeholder summary and allowing job to succeed"
            printf '{"error":"compute_failed","at":"%s"}\n' "$(date -Iseconds)" > "$outfile"
            echo "fallback=1" >> "$GITHUB_OUTPUT"
          else
            echo "fallback=0" >> "$GITHUB_OUTPUT"
          fi
          echo "summary_file=$outfile" >> "$GITHUB_OUTPUT"
          ls -la artifacts/ci || true
          head -20 "$outfile" || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-mavg-${{ github.run_id }}
          path: artifacts/ci/**
          if-no-files-found: warn

      - name: Step Summary
        run: |
          {
            echo "## CI Moving Average"
            echo "- Since days: ${{ inputs.since_days || '14' }}"
            echo "- Fallback used: ${{ steps.compute.outputs.fallback }}"
            echo "- Summary file: ${{ steps.compute.outputs.summary_file }}"
            echo
            echo '```json'
            head -20 "${{ steps.compute.outputs.summary_file }}" || true
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
