name: ci-mcp-api-boundary
on:
  pull_request:
    paths:
      - ".github/workflows/ci-mcp-api-boundary.yml"
      - "docs/CI/MCP_API_BOUNDARY_STAGE_C.md"
  workflow_dispatch:

jobs:
  api-boundary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Assert GET is allowed (repo metadata)
        run: |
          set -euo pipefail
          gh api /repos/${{ github.repository }} -q '.name' | grep -i ucomm
      - name: Assert POST is denied (must fail)
        run: |
          set -euo pipefail
          set +e
          gh api -X POST /repos/${{ github.repository }}/issues -f title="should-not-create" >/tmp/out 2>/tmp/err
          CODE=$?
          echo "exit=$CODE"
          # gh は失敗時に非0を返すはず。0 なら失敗として扱う
          if [ "$CODE" -eq 0 ]; then echo "POST unexpectedly succeeded"; cat /tmp/out; exit 1; fi
          # 403/404 を許容
          cat /tmp/err | (grep -E "HTTP 403|HTTP 404" && exit 0) || (echo "unexpected error code"; cat /tmp/err; exit 1)
      - name: Mask outputs
        run: |
          echo "::add-mask::${{ github.token }}"