name: Link Check
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Install lychee
        run: |
          curl -sSL https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv lychee /usr/local/bin/
      - name: Run lychee (direct command)
        run: |
          lychee --no-progress \
            --accept 200,201,202,203,204,206,207,226,429,999 \
            --exclude-path "artifacts/ci-remote/**" \
            --exclude-path ".git/**" \
            --exclude "https://github.com/.*/actions/runs/.*" \
            --exclude "https://github.com/.*/workflows/.*badge.*" \
            --exclude "https://x.com/.*" \
            --exclude "https://www.youtube.com/.*" \
            --exclude "https://qiita.com/.*" \
            --max-redirects 5 \
            --timeout 20 \
            --cache \
            --verbose \
            .