name: Minutes Smoke Test
on:
  pull_request:
    paths:
      - "scripts/**"
      - ".github/workflows/minutes.yml"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create test logs with trailing newlines
        run: |
          mkdir -p logs/local/2025-09-01
          cat > logs/local/2025-09-01/session_with_newlines.log << 'EOF'
          2025-09-01 10:00:00	director	[#topic] フェーズ5キックオフ
          2025-09-01 10:03:12	manager	決定: Link Check を必須（Public時のみ enforce）
          2025-09-01 10:05:00	specialist	TODO: minutes.sh の章立て実装を進める @alice
          EOF
          
      - name: Create test logs WITHOUT trailing newlines
        run: |
          # Create file without trailing newline using printf (no final \n)
          printf "2025-09-01 10:00:00\tdirector\t[#topic] フェーズ5キックオフ\n2025-09-01 10:03:12\tmanager\t決定: Link Check を必須（Public時のみ enforce）\n2025-09-01 10:05:00\tspecialist\tTODO: minutes.sh の章立て実装を進める @alice" > logs/local/2025-09-01/session_no_newline.log
          
      - name: Verify test data setup
        run: |
          echo "=== Files created ==="
          ls -la logs/local/2025-09-01/
          echo ""
          echo "=== With newlines (should end with newline) ==="
          hexdump -C logs/local/2025-09-01/session_with_newlines.log | tail -2
          echo ""  
          echo "=== Without newlines (should NOT end with newline) ==="
          hexdump -C logs/local/2025-09-01/session_no_newline.log | tail -2
          
      - name: Run minutes generation with newlines
        shell: bash
        run: |
          bash scripts/minutes.sh 2025-09-01 local
          test -f reports/minutes/2025-09-01/local.md
          
      - name: Verify all roles captured (with newlines case)
        run: |
          echo "=== Generated minutes content ==="
          cat reports/minutes/2025-09-01/local.md
          echo ""
          echo "=== Checking role counts ==="
          # Should find all three roles in the summary
          grep -q "director" reports/minutes/2025-09-01/local.md
          grep -q "manager" reports/minutes/2025-09-01/local.md  
          grep -q "specialist" reports/minutes/2025-09-01/local.md
          echo "✓ All roles found in minutes with trailing newlines"
          
      - name: Clean up and test no-trailing-newline case
        run: |
          rm -f reports/minutes/2025-09-01/local.md
          # Remove the file with newlines, keep only the no-newline version
          rm logs/local/2025-09-01/session_with_newlines.log
          
      - name: Run minutes generation WITHOUT trailing newlines
        shell: bash  
        run: |
          echo "=== Testing the critical case: no trailing newline ==="
          bash scripts/minutes.sh 2025-09-01 local
          test -f reports/minutes/2025-09-01/local.md
          
      - name: Verify all roles captured (no trailing newline case) 
        run: |
          echo "=== Generated minutes content (no trailing newline input) ==="
          cat reports/minutes/2025-09-01/local.md
          echo ""
          echo "=== Critical test: specialist role should be captured ==="
          # The key test: specialist was the last line without trailing newline
          if grep -q "specialist" reports/minutes/2025-09-01/local.md; then
            echo "✅ SUCCESS: specialist role captured despite no trailing newline"
          else
            echo "❌ FAILURE: specialist role missing - last line was dropped"
            exit 1
          fi
          
          # Verify all roles are present
          grep -q "director" reports/minutes/2025-09-01/local.md
          grep -q "manager" reports/minutes/2025-09-01/local.md
          echo "✓ All roles successfully captured from input without trailing newline"
          
      - name: Run mask tests
        shell: bash
        run: |
          if [ -f tests/test_mask.sh ]; then
            echo "=== Running mask unit tests ==="
            bash tests/test_mask.sh
          else
            echo "⚠ No mask tests found, skipping"
          fi
          
      - name: Run minutes last-line unit test
        shell: bash
        run: |
          if [ -f tests/test_minutes_last_line.sh ]; then
            echo "=== Running last-line regression test ==="
            bash tests/test_minutes_last_line.sh
          else
            echo "⚠ Last-line regression test not found, skipping"
          fi
          
      - name: Upload artifacts on success
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: minutes-artifacts
          path: |
            logs/local/**
            reports/minutes/**
          retention-days: 7
          
      - name: Summary
        run: |
          echo ""
          echo "🎉 SUCCESS: Minutes generation hardened!"
          echo "✅ Handles inputs with trailing newlines"
          echo "✅ Handles inputs WITHOUT trailing newlines" 
          echo "✅ All roles captured in both scenarios"
          echo "✅ Masking functions working correctly"
          echo "✅ Last-line regression test passed"