name: Promote CI Artifacts to Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v0.5.0-phase4.3-proof)"
        required: true
      artifacts_dir:
        description: "Local path to collected artifacts (e.g. artifacts/ci-remote/20250828_215253)"
        required: true
      release_name:
        description: "Release name (optional)"
        required: false
      body:
        description: "Release notes (optional)"
        required: false

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate inputs
        run: |
          test -n "${{ github.event.inputs.tag }}"
          test -n "${{ github.event.inputs.artifacts_dir }}"

      - name: Zip artifacts
        run: |
          dir="${{ github.event.inputs.artifacts_dir }}"
          test -d "$dir"
          zip -r "ucomm-artifacts-${{ github.event.inputs.tag }}.zip" "$dir"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name || github.event.inputs.tag }}
          body: ${{ github.event.inputs.body }}
          draft: false
          prerelease: false
          files: |
            ucomm-artifacts-${{ github.event.inputs.tag }}.zip