name: smoke

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/smoke.yml"
      - "scripts/**"
      - "config/**"
      - "ucomm.sh"
      - "docs/**"
      - "package.json"
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      secure_mode:
        description: "SECURE_MODE (0=スタブ, 1=実運用)"
        type: choice
        required: true
        default: "0"
        options: ["0","1"]
      run_capture:
        description: "logs を artifacts に添付する"
        type: boolean
        required: false
        default: true

permissions:
  contents: read

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

env:
  # repo Variables に UCOMM_SECURE_MODE が無ければ '0'
  UCOMM_SECURE_MODE: ${{ vars.UCOMM_SECURE_MODE || '0' }}
  TZ: Asia/Tokyo

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps (tmux/jq/curl/yq)
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux jq curl xz-utils ca-certificates
          sudo curl -fsSL -o /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm deps
        run: |
          npm ci || npm install

      - name: Launch (SECURE_MODE=${{ inputs.secure_mode || env.UCOMM_SECURE_MODE }})
        env:
          UCOMM_SECURE_MODE: ${{ inputs.secure_mode || env.UCOMM_SECURE_MODE }}
        run: |
          ./ucomm.sh start "$UCOMM_SECURE_MODE"

      - name: Health
        run: |
          scripts/health.sh --json | tee health.json
          jq -r '.summary.status' health.json | grep -q '^ok$'

      - name: Capture (optional)
        if: ${{ inputs.run_capture }}
        run: |
          scripts/capture.sh --once
          echo "captured=1" >> $GITHUB_OUTPUT

      - name: Upload logs
        if: ${{ inputs.run_capture }}
        uses: actions/upload-artifact@v4
        with:
          name: smoke-logs
          path: |
            logs/**/**/*.log
          if-no-files-found: warn
          retention-days: 7

      - name: Summarize
        run: |
          {
            echo "### smoke summary"
            echo ""
            echo "- SECURE_MODE: \`${{ inputs.secure_mode || env.UCOMM_SECURE_MODE }}\`"
            echo "- capture: \`${{ inputs.run_capture && 'true' || 'false' }}\`"
            echo "- health: \`$(jq -r '.summary.status' health.json)\`"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Teardown
        if: always()
        run: ./ucomm.sh stop || true
