name: smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      UCOMM_SECURE_MODE: "0"   # 本番のみ "1"
      MCP_LATENCY_MAX: "6.0"   # CI 基準

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install runtime deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux jq yq

      - name: Launch (MCP→tmux→CLI)
        run: |
          chmod +x scripts/*.sh
          # 起動
          scripts/ucomm-launch.sh & echo $! > /tmp/ucomm_pid
          # health (JSON) の可読化と閾値判定
          scripts/health.sh --json | tee /tmp/health.json
          jq . /tmp/health.json >/dev/null
          # /ready 到達時間の閾値チェック
          LAT=$(jq -r '.summary.mcp.latency_ms' /tmp/health.json)
          echo "MCP /ready latency (ms): $LAT"
          awk -v ms="$LAT" -v max="$(echo "${MCP_LATENCY_MAX}*1000" | bc)" 'BEGIN{ exit (ms<=max)?0:1 }'

      - name: Capture logs (single pass)
        run: |
          scripts/capture.sh --once || true
          find logs -type f -maxdepth 3 | sed -n '1,100p'

      - name: Upload logs (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-logs
          path: logs

      - name: Teardown
        if: always()
        run: |
          kill -TERM "$(cat /tmp/ucomm_pid)" 2>/dev/null || true
